Importing Numpy

In [1]:
import numpy as np

Importing Pandas and displaying the five random data from the dataset

In [2]:
import pandas as pd

df = pd.read_csv("Dataset-SA.csv")

df.sample(5)

,product_name,product_price,Rate,Review,Summary,Sentiment
197481,cello Pack of 18 Opalware Cello Dazzle Lush Fi...,1299,1,waste of money!,product is lite small bt quality is good,positive
583,MAHARAJA WHITELINE 65 L Desert Air Cooler?????...,7999,1,don't waste your money,absolutely useless product please never buy it...,negative
97390,MarQ by Flipkart 18-Litre 18L1200W4HL Oven Toa...,2499,5,brilliant,excellent product performance unbelievablejust...,positive
54502,Men Graphic Print Round Neck White T-Shirt,269,4,NaN,good,positive
189565,SAMSUNG EVO Plus 64 GB MicroSDXC Class 10 95 M...,649,4,delightful,really good,positive

Checking the number of positive, negative and neutral sentiments in the dataset

In [3]:
df['Sentiment'].value_counts()

Sentiment
positive    166581
negative     28232
neutral      10239
Name: count, dtype: int64

ANALYSING THE DATASET

In [4]:
df.shape

(205052, 6)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 205052 entries, 0 to 205051
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   product_name   205052 non-null  str
 1   product_price  205052 non-null  str
 2   Rate           205052 non-null  str
 3   Review         180388 non-null  str
 4   Summary        205041 non-null  str
 5   Sentiment      205052 non-null  str
dtypes: str(6)
memory usage: 9.4 MB

Finding the number of missing values and ANALYSING THEM

In [6]:
df.isnull().sum()

product_name         0
product_price        0
Rate                 0
Review           24664
Summary             11
Sentiment            0
dtype: int64

In [7]:
df.isnull().mean()*100

product_name      0.000000
product_price     0.000000
Rate              0.000000
Review           12.028168
Summary           0.005364
Sentiment         0.000000
dtype: float64

In [8]:
df[df['Review'].isnull()].head()

,product_name,product_price,Rate,Review,Summary,Sentiment
41625,Top - Pyjama Set Thermal For Boys & Girls?????...,365,5,NaN,best product,positive
41626,Top - Pyjama Set Thermal For Boys & Girls?????...,365,5,NaN,very good,positive
41627,Top - Pyjama Set Thermal For Boys & Girls?????...,365,5,NaN,very comfortablegood qualitylove it,positive
41628,Top - Pyjama Set Thermal For Boys & Girls?????...,365,5,NaN,very soft and comfortable go for it,positive
41629,Top - Pyjama Set Thermal For Boys & Girls?????...,365,5,NaN,super product quality is vry good tnx flipkart,positive

In [9]:
df[df['Review'].isnull()][['Summary','Rate','Sentiment']].head(10)

                                                 Summary Rate Sentiment
41625                                       best product    5  positive
41626                                          very good    5  positive
41627                very comfortablegood qualitylove it    5  positive
41628                very soft and comfortable go for it    5  positive
41629     super product quality is vry good tnx flipkart    5  positive
41630  fits her perfectly and good quality for winter...    5  positive
41631                                       same product    5  positive
41632                                        soft febric    4  positive
41633                        great innershine and warmth    5  positive
41634                                     superb product    5  positive

In [10]:
df[df['Review'].isnull()]['Sentiment'].value_counts()

Sentiment
positive    19405
negative     3831
neutral      1428
Name: count, dtype: int64

In [11]:
df.columns

Index(['product_name', 'product_price', 'Rate', 'Review', 'Summary',
       'Sentiment'],
      dtype='str')

In [12]:
df['Rate'].value_counts()

Rate
5                                                                    118765
4                                                                     41894
1                                                                     21300
3                                                                     16599
2                                                                      6491
Pigeon Favourite Electric Kettle??????(1.5 L, Silver, Black)              1
Bajaj DX 2 L/W Dry Iron                                                   1
Nova Plus Amaze NI 10 1100 W Dry Iron?ÃÂ¿?ÃÂ¿(Grey & Turquoise)         1
Name: count, dtype: int64

In [13]:
pd.crosstab(df['Rate'],df['Sentiment'])

Sentiment,negative,neutral,positive
Rate,,,
1,18793,1233,1274
2,4707,1050,734
3,3023,3660,9916
4,882,1982,39030
5,826,2314,115625
Bajaj DX 2 L/W Dry Iron,1,0,0
Nova Plus Amaze NI 10 1100 W Dry Iron?ÃÂ¿?ÃÂ¿(Grey & Turquoise),0,0,1
"Pigeon Favourite Electric Kettle??????(1.5 L, Silver, Black)",0,0,1

In [14]:
df[df['Review'].isnull()]['Summary'].isnull().sum()

np.int64(2)

In [15]:
df.loc[(df['Review'].isnull()) & df['Summary'].isnull()]

,product_name,product_price,Rate,Review,Summary,Sentiment
47616,Men Casual Brown Artificial Leather Money Clip...,159,5,NaN,NaN,positive
50559,Men Cargos,499,2,NaN,NaN,neutral

In [16]:
df.loc[df['Review'].isnull(), 'Review'] = df.loc[df['Review'].isnull(), 'Summary']

In [17]:
df = df.dropna(subset=('Review','Summary'), how='all')

In [18]:
df.info()

<class 'pandas.DataFrame'>
Index: 205050 entries, 0 to 205051
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   product_name   205050 non-null  str
 1   product_price  205050 non-null  str
 2   Rate           205050 non-null  str
 3   Review         205050 non-null  str
 4   Summary        205041 non-null  str
 5   Sentiment      205050 non-null  str
dtypes: str(6)
memory usage: 11.0 MB

Creating a column 'text' and storing the review in it

In [20]:
df['Text'] = df['Review']

In [21]:
df[['Review','Text','Sentiment']].sample(5)

,Review,Text,Sentiment
76423,superb,superb,positive
175635,pretty good,pretty good,neutral
24677,bad quality,bad quality,positive
49379,nice blazer good quality very nice productthan...,nice blazer good quality very nice productthan...,positive
103315,good product,good product,positive

In [22]:
df['Sentiment'].value_counts()

Sentiment
positive    166580
negative     28232
neutral      10238
Name: count, dtype: int64

TRAIN/TEST SPLIT

In [24]:
x = df['Text']

In [25]:
y = df['Sentiment']

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, Y_train, Y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [30]:
print("X_train",X_train.shape)
print("X_test",X_test.shape)
print("Y_train",Y_train.shape)
print("Y_test",Y_test.shape)

X_train (164040,)
X_test (41010,)
Y_train (164040,)
Y_test (41010,)

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

In [33]:
X_train_tfidf = tfidf.fit_transform(X_train)

In [34]:
X_test_tfidf = tfidf.transform(X_test)

In [36]:
print("Training : ",X_train_tfidf.shape)
print("Testing : ",X_test_tfidf.shape)

Training :  (164040, 4873)
Testing :  (41010, 4873)

USING LOGISTIC REGRESSION TO TRAIN THE MODEL

In [37]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train_tfidf, Y_train)

LogisticRegression(max_iter=1000)

PREDICTING and CHECKING THE MODELS ACCURACY

In [38]:
y_pred = model.predict(X_test_tfidf)

In [39]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(Y_test,y_pred)

print("Accuracy = ", accuracy)

Accuracy =  0.9152158010241405

In [40]:
from sklearn.metrics import confusion_matrix, classification_report

print("Confusion Matrix: ",confusion_matrix(Y_test,y_pred))

print("Classification Report: ",classification_report(Y_test,y_pred))

Confusion Matrix:  [[ 4437     6  1203]
 [  415   156  1477]
 [  349    27 32940]]
Classification Report:                precision    recall  f1-score   support

    negative       0.85      0.79      0.82      5646
     neutral       0.83      0.08      0.14      2048
    positive       0.92      0.99      0.96     33316

    accuracy                           0.92     41010
   macro avg       0.87      0.62      0.64     41010
weighted avg       0.91      0.92      0.90     41010

TESTING THE MODEL WITH NEW REVIEWS

In [41]:
new_reviews = [
    "This phone is amazing and the battery lasts all day.",
    "Very bad product, it stopped working after two days.",
    "This product is okay, nothing special."
]

new_reviews_tfidf = tfidf.transform(new_reviews)

prediction = model.predict(new_reviews_tfidf)

for review, prediction in zip(new_reviews, prediction):
    print("Review: ", review)
    print("Predicted Sentiment: ", prediction)
    print()

Review:  This phone is amazing and the battery lasts all day.
Predicted Sentiment:  positive

Review:  Very bad product, it stopped working after two days.
Predicted Sentiment:  negative

Review:  This product is okay, nothing special.
Predicted Sentiment:  positive

CREATING PIPELINE

In [42]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ('tfidf',TfidfVectorizer()),
    ('model', LogisticRegression(max_iter=1000))
])

In [43]:
pipeline.fit(X_train, Y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('model', LogisticRegression(max_iter=1000))])

In [44]:
y_pred_pipeline = pipeline.predict(X_test)

In [45]:
from sklearn.metrics import accuracy_score

pipeline_accuracy = accuracy_score(Y_test, y_pred_pipeline)

print("Pipeline Accuracy: ", pipeline_accuracy)

Pipeline Accuracy:  0.9152158010241405

In [46]:
import joblib

joblib.dump(pipeline, 'sentiment_pipeline.pkl')

['sentiment_pipeline.pkl']